// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for CodeLensOperations.
    /// </summary>
    public static partial class CodeLensOperationsExtensions
    {
            /// <summary>
            /// request to resolve the command for a given code lens item.
            /// </summary>
            /// <remarks>
            /// request to resolve the command for a given code lens item.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='codeLens'>
            /// Position within the text document.
            /// </param>
            public static object Resolve(this ICodeLensOperations operations, CodeLens codeLens = default(CodeLens))
            {
                return operations.ResolveAsync(codeLens).GetAwaiter().GetResult();
            }

            /// <summary>
            /// request to resolve the command for a given code lens item.
            /// </summary>
            /// <remarks>
            /// request to resolve the command for a given code lens item.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='codeLens'>
            /// Position within the text document.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ResolveAsync(this ICodeLensOperations operations, CodeLens codeLens = default(CodeLens), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ResolveWithHttpMessagesAsync(codeLens, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}

