// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for TextDocument.
    /// </summary>
    public static partial class TextDocumentExtensions
    {
            /// <summary>
            /// request to compute commands for a given text document and range.
            /// </summary>
            /// <remarks>
            /// request to compute commands for a given text document and range.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='workspaceSymbolParams'>
            /// Position within the text document.
            /// </param>
            public static object Symbol(this ITextDocument operations, CodeActionParams workspaceSymbolParams = default(CodeActionParams))
            {
                return operations.SymbolAsync(workspaceSymbolParams).GetAwaiter().GetResult();
            }

            /// <summary>
            /// request to compute commands for a given text document and range.
            /// </summary>
            /// <remarks>
            /// request to compute commands for a given text document and range.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='workspaceSymbolParams'>
            /// Position within the text document.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> SymbolAsync(this ITextDocument operations, CodeActionParams workspaceSymbolParams = default(CodeActionParams), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SymbolWithHttpMessagesAsync(workspaceSymbolParams, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}

