{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "license": {
      "name": "MIT"
    }
  },
  "paths": {
    "/SimpleAPI/GetStuff": {
      "post": {
        "description": "get the stuff",
        "summary": "gets current stuff",
        "operationId": "getTime",
        "parameters": [

        ],
        "responses": {
          "200": {
            "body": {
              "value": [
                {
                  "timeNow": "#definitions/Model2"
                }
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Model1": {
      "description": "The1",
      "properties": {
        "prop1":{
			"description":"prop1",
			"type":"string"
		}
      }
    },
	"Model2":{
		"description":"the2",
		"allOf":[{
		"$ref":"#/definitions/Model1"
		}
		]
		"prop2":{
			"description":"prop2",
			"type":"string"
		}
	}
  }
}