// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The capabilities provided by the client (editor or tool)
    /// </summary>
    public partial class ClientCapabilities
    {
        /// <summary>
        /// Initializes a new instance of the ClientCapabilities class.
        /// </summary>
        public ClientCapabilities() { }

        /// <summary>
        /// Initializes a new instance of the ClientCapabilities class.
        /// </summary>
        /// <param name="workspace">Workspace specific client
        /// capabilities.</param>
        /// <param name="textDocument">Text document specific client
        /// capabilities.</param>
        /// <param name="experimental">Experimental client
        /// capabilities.</param>
        public ClientCapabilities(WorkspaceClientCapabilities workspace = default(WorkspaceClientCapabilities), TextDocumentClientCapabilities textDocument = default(TextDocumentClientCapabilities), object experimental = default(object))
        {
            Workspace = workspace;
            TextDocument = textDocument;
            Experimental = experimental;
        }

        /// <summary>
        /// Gets or sets workspace specific client capabilities.
        /// </summary>
        [JsonProperty(PropertyName = "workspace")]
        public WorkspaceClientCapabilities Workspace { get; set; }

        /// <summary>
        /// Gets or sets text document specific client capabilities.
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentClientCapabilities TextDocument { get; set; }

        /// <summary>
        /// Gets or sets experimental client capabilities.
        /// </summary>
        [JsonProperty(PropertyName = "experimental")]
        public object Experimental { get; set; }

    }
}

