// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A code lens represents a command that should be shown along with source
    /// text, like the number of references, a way to run tests, etc.
    /// </summary>
    public partial class CodeLens
    {
        /// <summary>
        /// Initializes a new instance of the CodeLens class.
        /// </summary>
        public CodeLens() { }

        /// <summary>
        /// Initializes a new instance of the CodeLens class.
        /// </summary>
        /// <param name="range">The range in which this code lens is valid.
        /// Should only span a single line.</param>
        /// <param name="command">The command this code lens
        /// represents.</param>
        /// <param name="data">A data entry field that is preserved on a code
        /// lens item between a code lens and a code lens resolve
        /// request.</param>
        public CodeLens(Range range = default(Range), Command command = default(Command), object data = default(object))
        {
            Range = range;
            Command = command;
            Data = data;
        }

        /// <summary>
        /// Gets or sets the range in which this code lens is valid. Should
        /// only span a single line.
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

        /// <summary>
        /// Gets or sets the command this code lens represents.
        /// </summary>
        [JsonProperty(PropertyName = "command")]
        public Command Command { get; set; }

        /// <summary>
        /// Gets or sets a data entry field that is preserved on a code lens
        /// item between a code lens and a code lens resolve request.
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public object Data { get; set; }

    }
}

