// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Params for the CodeActionRequest
    /// </summary>
    public partial class CodeActionParams
    {
        /// <summary>
        /// Initializes a new instance of the CodeActionParams class.
        /// </summary>
        public CodeActionParams() { }

        /// <summary>
        /// Initializes a new instance of the CodeActionParams class.
        /// </summary>
        public CodeActionParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier), Range range = default(Range), CodeActionContext context = default(CodeActionContext))
        {
            TextDocument = textDocument;
            Range = range;
            Context = context;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "context")]
        public CodeActionContext Context { get; set; }

    }
}

