// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents a reference to a command.
    /// </summary>
    public partial class Command
    {
        /// <summary>
        /// Initializes a new instance of the Command class.
        /// </summary>
        public Command() { }

        /// <summary>
        /// Initializes a new instance of the Command class.
        /// </summary>
        /// <param name="title">Title of the command, like save.</param>
        /// <param name="commandProperty">The identifier of the actual command
        /// handler.</param>
        /// <param name="arguments">args for the command</param>
        public Command(string title = default(string), string commandProperty = default(string), IList<object> arguments = default(IList<object>))
        {
            Title = title;
            CommandProperty = commandProperty;
            Arguments = arguments;
        }

        /// <summary>
        /// Gets or sets title of the command, like save.
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the actual command handler.
        /// </summary>
        [JsonProperty(PropertyName = "command")]
        public string CommandProperty { get; set; }

        /// <summary>
        /// Gets or sets args for the command
        /// </summary>
        [JsonProperty(PropertyName = "arguments")]
        public IList<object> Arguments { get; set; }

    }
}

