// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The server provides completion support.
    /// </summary>
    public partial class CompletionOptions
    {
        /// <summary>
        /// Initializes a new instance of the CompletionOptions class.
        /// </summary>
        public CompletionOptions() { }

        /// <summary>
        /// Initializes a new instance of the CompletionOptions class.
        /// </summary>
        /// <param name="resolveProvider">The server provides support to
        /// resolve additional information for a completion item.</param>
        /// <param name="triggerCharacters">The characters that trigger
        /// completion automatically.</param>
        public CompletionOptions(bool? resolveProvider = default(bool?), IList<string> triggerCharacters = default(IList<string>))
        {
            ResolveProvider = resolveProvider;
            TriggerCharacters = triggerCharacters;
        }

        /// <summary>
        /// Gets or sets the server provides support to resolve additional
        /// information for a completion item.
        /// </summary>
        [JsonProperty(PropertyName = "resolveProvider")]
        public bool? ResolveProvider { get; set; }

        /// <summary>
        /// Gets or sets the characters that trigger completion automatically.
        /// </summary>
        [JsonProperty(PropertyName = "triggerCharacters")]
        public IList<string> TriggerCharacters { get; set; }

    }
}

