// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// completion items and metadata
    /// </summary>
    public partial class CompletionList
    {
        /// <summary>
        /// Initializes a new instance of the CompletionList class.
        /// </summary>
        public CompletionList() { }

        /// <summary>
        /// Initializes a new instance of the CompletionList class.
        /// </summary>
        /// <param name="isIncomplete">This list it not complete. Further
        /// typing should result in recomputing this list.</param>
        public CompletionList(IList<CompletionItem> items = default(IList<CompletionItem>), bool? isIncomplete = default(bool?))
        {
            Items = items;
            IsIncomplete = isIncomplete;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<CompletionItem> Items { get; set; }

        /// <summary>
        /// Gets or sets this list it not complete. Further typing should
        /// result in recomputing this list.
        /// </summary>
        [JsonProperty(PropertyName = "isIncomplete")]
        public bool? IsIncomplete { get; set; }

    }
}

