// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// changes to document
    /// </summary>
    public partial class DidChangeTextDocumentParams
    {
        /// <summary>
        /// Initializes a new instance of the DidChangeTextDocumentParams
        /// class.
        /// </summary>
        public DidChangeTextDocumentParams() { }

        /// <summary>
        /// Initializes a new instance of the DidChangeTextDocumentParams
        /// class.
        /// </summary>
        /// <param name="contentChanges">The actual content changes.</param>
        public DidChangeTextDocumentParams(VersionedTextDocumentIdentifier textDocument = default(VersionedTextDocumentIdentifier), IList<TextDocumentContentChangeEvent> contentChanges = default(IList<TextDocumentContentChangeEvent>))
        {
            TextDocument = textDocument;
            ContentChanges = contentChanges;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public VersionedTextDocumentIdentifier TextDocument { get; set; }

        /// <summary>
        /// Gets or sets the actual content changes.
        /// </summary>
        [JsonProperty(PropertyName = "contentChanges")]
        public IList<TextDocumentContentChangeEvent> ContentChanges { get; set; }

    }
}

