// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// info about the closed doc
    /// </summary>
    public partial class DidCloseTextDocumentParamsModel
    {
        /// <summary>
        /// Initializes a new instance of the DidCloseTextDocumentParamsModel
        /// class.
        /// </summary>
        public DidCloseTextDocumentParamsModel() { }

        /// <summary>
        /// Initializes a new instance of the DidCloseTextDocumentParamsModel
        /// class.
        /// </summary>
        public DidCloseTextDocumentParamsModel(DidCloseTextDocumentParams textDocument = default(DidCloseTextDocumentParams))
        {
            TextDocument = textDocument;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public DidCloseTextDocumentParams TextDocument { get; set; }

    }
}

