// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The server provides document link support.
    /// </summary>
    public partial class DocumentLinkOptions
    {
        /// <summary>
        /// Initializes a new instance of the DocumentLinkOptions class.
        /// </summary>
        public DocumentLinkOptions() { }

        /// <summary>
        /// Initializes a new instance of the DocumentLinkOptions class.
        /// </summary>
        public DocumentLinkOptions(bool? resolveProvider = default(bool?))
        {
            ResolveProvider = resolveProvider;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resolveProvider")]
        public bool? ResolveProvider { get; set; }

    }
}

