// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// document symbols
    /// </summary>
    public partial class DocumentSymbolParams
    {
        /// <summary>
        /// Initializes a new instance of the DocumentSymbolParams class.
        /// </summary>
        public DocumentSymbolParams() { }

        /// <summary>
        /// Initializes a new instance of the DocumentSymbolParams class.
        /// </summary>
        public DocumentSymbolParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier))
        {
            TextDocument = textDocument;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; set; }

    }
}

