// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A document highlight is a range inside a text document which deserves
    /// special attention. Usually a document highlight is visualized by
    /// changing the background color of its range.
    /// </summary>
    public partial class DocumentHighlight
    {
        /// <summary>
        /// Initializes a new instance of the DocumentHighlight class.
        /// </summary>
        public DocumentHighlight() { }

        /// <summary>
        /// Initializes a new instance of the DocumentHighlight class.
        /// </summary>
        /// <param name="kind">DocumentHighlightKind enum Text = 1, Read = 2,
        /// Write = 3;</param>
        public DocumentHighlight(Range range = default(Range), int? kind = default(int?))
        {
            Range = range;
            Kind = kind;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

        /// <summary>
        /// Gets or sets documentHighlightKind enum Text = 1, Read = 2, Write =
        /// 3;
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public int? Kind { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Kind > 3)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Kind", 3);
            }
            if (Kind < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Kind", 1);
            }
        }
    }
}

