// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// params to request fomratting of whole doc
    /// </summary>
    public partial class DocumentFormattingParams
    {
        /// <summary>
        /// Initializes a new instance of the DocumentFormattingParams class.
        /// </summary>
        public DocumentFormattingParams() { }

        /// <summary>
        /// Initializes a new instance of the DocumentFormattingParams class.
        /// </summary>
        public DocumentFormattingParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier), FormattingOptions options = default(FormattingOptions))
        {
            TextDocument = textDocument;
            Options = options;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "options")]
        public FormattingOptions Options { get; set; }

    }
}

