// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// params to format on typing
    /// </summary>
    public partial class DocumentOnTypeFormattingParams
    {
        /// <summary>
        /// Initializes a new instance of the DocumentOnTypeFormattingParams
        /// class.
        /// </summary>
        public DocumentOnTypeFormattingParams() { }

        /// <summary>
        /// Initializes a new instance of the DocumentOnTypeFormattingParams
        /// class.
        /// </summary>
        /// <param name="ch">The character that has been typed.</param>
        public DocumentOnTypeFormattingParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier), Position position = default(Position), string ch = default(string), FormattingOptions options = default(FormattingOptions))
        {
            TextDocument = textDocument;
            Position = position;
            Ch = ch;
            Options = options;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "position")]
        public Position Position { get; set; }

        /// <summary>
        /// Gets or sets the character that has been typed.
        /// </summary>
        [JsonProperty(PropertyName = "ch")]
        public string Ch { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "options")]
        public FormattingOptions Options { get; set; }

    }
}

