// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// req get location of links in a doc
    /// </summary>
    public partial class DocumentLinkParams
    {
        /// <summary>
        /// Initializes a new instance of the DocumentLinkParams class.
        /// </summary>
        public DocumentLinkParams() { }

        /// <summary>
        /// Initializes a new instance of the DocumentLinkParams class.
        /// </summary>
        public DocumentLinkParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier))
        {
            TextDocument = textDocument;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; set; }

    }
}

