// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Range over which to perform formatting
    /// </summary>
    public partial class DocumentRangeFormattingParams : DocumentFormattingParams
    {
        /// <summary>
        /// Initializes a new instance of the DocumentRangeFormattingParams
        /// class.
        /// </summary>
        public DocumentRangeFormattingParams() { }

        /// <summary>
        /// Initializes a new instance of the DocumentRangeFormattingParams
        /// class.
        /// </summary>
        public DocumentRangeFormattingParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier), FormattingOptions options = default(FormattingOptions), Range range = default(Range))
            : base(textDocument, options)
        {
            Range = range;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

    }
}

