// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A document link is a range in a text document that links to an internal
    /// or external resource, like another text document or a web site.
    /// </summary>
    public partial class DocumentLink
    {
        /// <summary>
        /// Initializes a new instance of the DocumentLink class.
        /// </summary>
        public DocumentLink() { }

        /// <summary>
        /// Initializes a new instance of the DocumentLink class.
        /// </summary>
        /// <param name="target">The uri this link points to.</param>
        public DocumentLink(Range range = default(Range), string target = default(string))
        {
            Range = range;
            Target = target;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

        /// <summary>
        /// Gets or sets the uri this link points to.
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

    }
}

