// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Execute command options.
    /// </summary>
    public partial class ExecuteCommandOptions
    {
        /// <summary>
        /// Initializes a new instance of the ExecuteCommandOptions class.
        /// </summary>
        public ExecuteCommandOptions() { }

        /// <summary>
        /// Initializes a new instance of the ExecuteCommandOptions class.
        /// </summary>
        /// <param name="commands">The commands to be executed on the
        /// server</param>
        public ExecuteCommandOptions(IList<string> commands = default(IList<string>))
        {
            Commands = commands;
        }

        /// <summary>
        /// Gets or sets the commands to be executed on the server
        /// </summary>
        [JsonProperty(PropertyName = "commands")]
        public IList<string> Commands { get; set; }

    }
}

