// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An event describing a file change.
    /// </summary>
    public partial class FileEvent
    {
        /// <summary>
        /// Initializes a new instance of the FileEvent class.
        /// </summary>
        public FileEvent() { }

        /// <summary>
        /// Initializes a new instance of the FileEvent class.
        /// </summary>
        /// <param name="uri">file's uri</param>
        /// <param name="type">the change type enum. Created = 1, Changed = 2,
        /// Deleted = 3</param>
        public FileEvent(string uri = default(string), int? type = default(int?))
        {
            Uri = uri;
            Type = type;
        }

        /// <summary>
        /// Gets or sets file's uri
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

        /// <summary>
        /// Gets or sets the change type enum. Created = 1, Changed = 2,
        /// Deleted = 3
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Type > 3)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Type", 3);
            }
            if (Type < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Type", 1);
            }
        }
    }
}

