// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Value-object describing what options formatting should use.
    /// </summary>
    public partial class FormattingOptions
    {
        /// <summary>
        /// Initializes a new instance of the FormattingOptions class.
        /// </summary>
        public FormattingOptions() { }

        /// <summary>
        /// Initializes a new instance of the FormattingOptions class.
        /// </summary>
        /// <param name="tabSize">Size of a tab in spaces.</param>
        /// <param name="insertSpaces">Prefer spaces over tabs.</param>
        public FormattingOptions(int? tabSize = default(int?), bool? insertSpaces = default(bool?))
        {
            TabSize = tabSize;
            InsertSpaces = insertSpaces;
        }

        /// <summary>
        /// Gets or sets size of a tab in spaces.
        /// </summary>
        [JsonProperty(PropertyName = "tabSize")]
        public int? TabSize { get; set; }

        /// <summary>
        /// Gets or sets prefer spaces over tabs.
        /// </summary>
        [JsonProperty(PropertyName = "insertSpaces")]
        public bool? InsertSpaces { get; set; }

    }
}

