// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The result of a hover request.
    /// </summary>
    public partial class Hover
    {
        /// <summary>
        /// Initializes a new instance of the Hover class.
        /// </summary>
        public Hover() { }

        /// <summary>
        /// Initializes a new instance of the Hover class.
        /// </summary>
        /// <param name="contents">array of marked strings</param>
        public Hover(IList<MarkedString> contents = default(IList<MarkedString>), Range range = default(Range))
        {
            Contents = contents;
            Range = range;
        }

        /// <summary>
        /// Gets or sets array of marked strings
        /// </summary>
        [JsonProperty(PropertyName = "contents")]
        public IList<MarkedString> Contents { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

    }
}

