// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// label and doc info
    /// </summary>
    public partial class LabelAndDocumentation
    {
        /// <summary>
        /// Initializes a new instance of the LabelAndDocumentation class.
        /// </summary>
        public LabelAndDocumentation() { }

        /// <summary>
        /// Initializes a new instance of the LabelAndDocumentation class.
        /// </summary>
        /// <param name="label">label for item</param>
        /// <param name="documentation">doc for item</param>
        public LabelAndDocumentation(string label = default(string), string documentation = default(string))
        {
            Label = label;
            Documentation = documentation;
        }

        /// <summary>
        /// Gets or sets label for item
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or sets doc for item
        /// </summary>
        [JsonProperty(PropertyName = "documentation")]
        public string Documentation { get; set; }

    }
}

