// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a location inside a resource, such as a line inside a text
    /// file.
    /// </summary>
    public partial class Location
    {
        /// <summary>
        /// Initializes a new instance of the Location class.
        /// </summary>
        public Location() { }

        /// <summary>
        /// Initializes a new instance of the Location class.
        /// </summary>
        /// <param name="uri">uri of the resource</param>
        public Location(string uri = default(string), Range range = default(Range))
        {
            Uri = uri;
            Range = range;
        }

        /// <summary>
        /// Gets or sets uri of the resource
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

    }
}

