// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// MarkedString can be used to render human readable text. It is either a
    /// markdown string or a code-block that provides a language and a code
    /// snippet.
    /// </summary>
    public partial class MarkedString
    {
        /// <summary>
        /// Initializes a new instance of the MarkedString class.
        /// </summary>
        public MarkedString() { }

        /// <summary>
        /// Initializes a new instance of the MarkedString class.
        /// </summary>
        /// <param name="language">lang of string</param>
        /// <param name="value">value of the string</param>
        public MarkedString(string language = default(string), string value = default(string))
        {
            Language = language;
            Value = value;
        }

        /// <summary>
        /// Gets or sets lang of string
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// Gets or sets value of the string
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}

