// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using System.Linq;

    /// <summary>
    /// Represents a parameter of a callable-signature. A parameter can have a
    /// label and a doc-comment.
    /// </summary>
    public partial class ParameterInformation : LabelAndDocumentation
    {
        /// <summary>
        /// Initializes a new instance of the ParameterInformation class.
        /// </summary>
        public ParameterInformation() { }

        /// <summary>
        /// Initializes a new instance of the ParameterInformation class.
        /// </summary>
        /// <param name="label">label for item</param>
        /// <param name="documentation">doc for item</param>
        public ParameterInformation(string label = default(string), string documentation = default(string))
            : base(label, documentation)
        {
        }

    }
}

