// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Position in a text document expressed as zero-based line and character
    /// offset
    /// </summary>
    public partial class Position
    {
        /// <summary>
        /// Initializes a new instance of the Position class.
        /// </summary>
        public Position() { }

        /// <summary>
        /// Initializes a new instance of the Position class.
        /// </summary>
        /// <param name="line">Line position in a document
        /// (zero-based).</param>
        /// <param name="character">Character offset on a line in a document
        /// (zero-based).</param>
        public Position(double? line = default(double?), double? character = default(double?))
        {
            Line = line;
            Character = character;
        }

        /// <summary>
        /// Gets or sets line position in a document (zero-based).
        /// </summary>
        [JsonProperty(PropertyName = "line")]
        public double? Line { get; set; }

        /// <summary>
        /// Gets or sets character offset on a line in a document (zero-based).
        /// </summary>
        [JsonProperty(PropertyName = "character")]
        public double? Character { get; set; }

    }
}

