// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// range of a document
    /// </summary>
    public partial class Range
    {
        /// <summary>
        /// Initializes a new instance of the Range class.
        /// </summary>
        public Range() { }

        /// <summary>
        /// Initializes a new instance of the Range class.
        /// </summary>
        public Range(Position start = default(Position), Position end = default(Position))
        {
            Start = start;
            End = end;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public Position Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "end")]
        public Position End { get; set; }

    }
}

