// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// params to rename a symbol
    /// </summary>
    public partial class RenameParams
    {
        /// <summary>
        /// Initializes a new instance of the RenameParams class.
        /// </summary>
        public RenameParams() { }

        /// <summary>
        /// Initializes a new instance of the RenameParams class.
        /// </summary>
        /// <param name="newName">new name for the symbol</param>
        public RenameParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier), Position position = default(Position), string newName = default(string))
        {
            TextDocument = textDocument;
            Position = position;
            NewName = newName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "position")]
        public Position Position { get; set; }

        /// <summary>
        /// Gets or sets new name for the symbol
        /// </summary>
        [JsonProperty(PropertyName = "newName")]
        public string NewName { get; set; }

    }
}

