// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Save notifications are sent to the server.
    /// </summary>
    public partial class SaveOptions
    {
        /// <summary>
        /// Initializes a new instance of the SaveOptions class.
        /// </summary>
        public SaveOptions() { }

        /// <summary>
        /// Initializes a new instance of the SaveOptions class.
        /// </summary>
        /// <param name="includeText">The client is supposed to include the
        /// content on save.</param>
        public SaveOptions(bool? includeText = default(bool?))
        {
            IncludeText = includeText;
        }

        /// <summary>
        /// Gets or sets the client is supposed to include the content on save.
        /// </summary>
        [JsonProperty(PropertyName = "includeText")]
        public bool? IncludeText { get; set; }

    }
}

