// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Signature help represents the signature of something  callable. There
    /// can be multiple signature but only one active and only one active
    /// parameter.
    /// </summary>
    public partial class SignatureHelp
    {
        /// <summary>
        /// Initializes a new instance of the SignatureHelp class.
        /// </summary>
        public SignatureHelp() { }

        /// <summary>
        /// Initializes a new instance of the SignatureHelp class.
        /// </summary>
        /// <param name="signatures">One or more signatures.</param>
        /// <param name="activeSignature">the active signature</param>
        /// <param name="activeParameter">the active param of active
        /// signature</param>
        public SignatureHelp(IList<SignatureInformation> signatures = default(IList<SignatureInformation>), int? activeSignature = default(int?), int? activeParameter = default(int?))
        {
            Signatures = signatures;
            ActiveSignature = activeSignature;
            ActiveParameter = activeParameter;
        }

        /// <summary>
        /// Gets or sets one or more signatures.
        /// </summary>
        [JsonProperty(PropertyName = "signatures")]
        public IList<SignatureInformation> Signatures { get; set; }

        /// <summary>
        /// Gets or sets the active signature
        /// </summary>
        [JsonProperty(PropertyName = "activeSignature")]
        public int? ActiveSignature { get; set; }

        /// <summary>
        /// Gets or sets the active param of active signature
        /// </summary>
        [JsonProperty(PropertyName = "activeParameter")]
        public int? ActiveParameter { get; set; }

    }
}

