// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The server provides signature help support.
    /// </summary>
    public partial class SignatureHelpOptions
    {
        /// <summary>
        /// Initializes a new instance of the SignatureHelpOptions class.
        /// </summary>
        public SignatureHelpOptions() { }

        /// <summary>
        /// Initializes a new instance of the SignatureHelpOptions class.
        /// </summary>
        /// <param name="triggerCharacters">The characters that trigger
        /// completion automatically.</param>
        public SignatureHelpOptions(IList<string> triggerCharacters = default(IList<string>))
        {
            TriggerCharacters = triggerCharacters;
        }

        /// <summary>
        /// Gets or sets the characters that trigger completion automatically.
        /// </summary>
        [JsonProperty(PropertyName = "triggerCharacters")]
        public IList<string> TriggerCharacters { get; set; }

    }
}

