// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Capabilities specific to the textDocument/hover
    /// </summary>
    public partial class TextDocumentClientCapabilitiesRangeFormatting
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesRangeFormatting class.
        /// </summary>
        public TextDocumentClientCapabilitiesRangeFormatting() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesRangeFormatting class.
        /// </summary>
        /// <param name="dynamicRegistration">Whether range formatting supports
        /// dynamic registration.</param>
        public TextDocumentClientCapabilitiesRangeFormatting(bool? dynamicRegistration = default(bool?))
        {
            DynamicRegistration = dynamicRegistration;
        }

        /// <summary>
        /// Gets or sets whether range formatting supports dynamic
        /// registration.
        /// </summary>
        [JsonProperty(PropertyName = "dynamicRegistration")]
        public bool? DynamicRegistration { get; set; }

    }
}

