// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines how text documents are synced. Is either a detailed structure
    /// defining each notification or for backwards compatibility the
    /// TextDocumentSyncKind number.
    /// </summary>
    public partial class TextDocumentSyncOptions
    {
        /// <summary>
        /// Initializes a new instance of the TextDocumentSyncOptions class.
        /// </summary>
        public TextDocumentSyncOptions() { }

        /// <summary>
        /// Initializes a new instance of the TextDocumentSyncOptions class.
        /// </summary>
        /// <param name="openClose">Open and close notifications are sent to
        /// the server.</param>
        /// <param name="change">Change notificatins are sent to the server.
        /// See TextDocumentSyncKind.None, TextDocumentSyncKind.Full and
        /// TextDocumentSyncKindIncremental.</param>
        /// <param name="willSave">Will save notifications are sent to the
        /// server.</param>
        /// <param name="willSaveWaitUntil">Will save wait until requests are
        /// sent to the server.</param>
        /// <param name="save">Save notifications are sent to the
        /// server.</param>
        public TextDocumentSyncOptions(bool? openClose = default(bool?), int? change = default(int?), bool? willSave = default(bool?), bool? willSaveWaitUntil = default(bool?), SaveOptions save = default(SaveOptions))
        {
            OpenClose = openClose;
            Change = change;
            WillSave = willSave;
            WillSaveWaitUntil = willSaveWaitUntil;
            Save = save;
        }

        /// <summary>
        /// Gets or sets open and close notifications are sent to the server.
        /// </summary>
        [JsonProperty(PropertyName = "openClose")]
        public bool? OpenClose { get; set; }

        /// <summary>
        /// Gets or sets change notificatins are sent to the server. See
        /// TextDocumentSyncKind.None, TextDocumentSyncKind.Full and
        /// TextDocumentSyncKindIncremental.
        /// </summary>
        [JsonProperty(PropertyName = "change")]
        public int? Change { get; set; }

        /// <summary>
        /// Gets or sets will save notifications are sent to the server.
        /// </summary>
        [JsonProperty(PropertyName = "willSave")]
        public bool? WillSave { get; set; }

        /// <summary>
        /// Gets or sets will save wait until requests are sent to the server.
        /// </summary>
        [JsonProperty(PropertyName = "WillSaveWaitUntil")]
        public bool? WillSaveWaitUntil { get; set; }

        /// <summary>
        /// Gets or sets save notifications are sent to the server.
        /// </summary>
        [JsonProperty(PropertyName = "save")]
        public SaveOptions Save { get; set; }

    }
}

