// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Capabilities specific to the textDocument/hover
    /// </summary>
    public partial class TextDocumentClientCapabilitiesCodeLens
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesCodeLens class.
        /// </summary>
        public TextDocumentClientCapabilitiesCodeLens() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesCodeLens class.
        /// </summary>
        /// <param name="dynamicRegistration">Whether code lens supports
        /// dynamic registration.</param>
        public TextDocumentClientCapabilitiesCodeLens(bool? dynamicRegistration = default(bool?))
        {
            DynamicRegistration = dynamicRegistration;
        }

        /// <summary>
        /// Gets or sets whether code lens supports dynamic registration.
        /// </summary>
        [JsonProperty(PropertyName = "dynamicRegistration")]
        public bool? DynamicRegistration { get; set; }

    }
}

