// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Capabilities specific to the textDocument/references
    /// </summary>
    public partial class TextDocumentClientCapabilitiesDocumentHighlight
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesDocumentHighlight class.
        /// </summary>
        public TextDocumentClientCapabilitiesDocumentHighlight() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesDocumentHighlight class.
        /// </summary>
        /// <param name="dynamicRegistration">Whether document highlight
        /// supports dynamic registration.</param>
        public TextDocumentClientCapabilitiesDocumentHighlight(bool? dynamicRegistration = default(bool?))
        {
            DynamicRegistration = dynamicRegistration;
        }

        /// <summary>
        /// Gets or sets whether document highlight supports dynamic
        /// registration.
        /// </summary>
        [JsonProperty(PropertyName = "dynamicRegistration")]
        public bool? DynamicRegistration { get; set; }

    }
}

