// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The client supports the following CompletionItem specific capabilities.
    /// </summary>
    public partial class TextDocumentClientCapabilitiesCompletionCompletionItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesCompletionCompletionItem class.
        /// </summary>
        public TextDocumentClientCapabilitiesCompletionCompletionItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesCompletionCompletionItem class.
        /// </summary>
        /// <param name="snippetSupport">Client supports snippets as insert
        /// text. A snippet can define tab stops and placeholders with `$1`,
        /// `$2` and `${3:foo}`. `$0` defines the final tab stop, it defaults
        /// to the end of the snippet. Placeholders with equal identifiers are
        /// linked, that is typing in one will update others too.</param>
        public TextDocumentClientCapabilitiesCompletionCompletionItem(bool? snippetSupport = default(bool?))
        {
            SnippetSupport = snippetSupport;
        }

        /// <summary>
        /// Gets or sets client supports snippets as insert text. A snippet can
        /// define tab stops and placeholders with `$1`, `$2` and `${3:foo}`.
        /// `$0` defines the final tab stop, it defaults to the end of the
        /// snippet. Placeholders with equal identifiers are linked, that is
        /// typing in one will update others too.
        /// </summary>
        [JsonProperty(PropertyName = "snippetSupport")]
        public bool? SnippetSupport { get; set; }

    }
}

