// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// editing to be performed
    /// </summary>
    public partial class TextEdit
    {
        /// <summary>
        /// Initializes a new instance of the TextEdit class.
        /// </summary>
        public TextEdit() { }

        /// <summary>
        /// Initializes a new instance of the TextEdit class.
        /// </summary>
        /// <param name="newText">The string to be inserted. For delete
        /// operations use an empty string.</param>
        public TextEdit(Range range = default(Range), string newText = default(string))
        {
            Range = range;
            NewText = newText;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

        /// <summary>
        /// Gets or sets the string to be inserted. For delete operations use
        /// an empty string.
        /// </summary>
        [JsonProperty(PropertyName = "newText")]
        public string NewText { get; set; }

    }
}

