// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An event describing a change to a text document. If range and
    /// rangeLength are omitted the new text is considered to be the full
    /// content of the document.
    /// </summary>
    public partial class TextDocumentContentChangeEvent
    {
        /// <summary>
        /// Initializes a new instance of the TextDocumentContentChangeEvent
        /// class.
        /// </summary>
        public TextDocumentContentChangeEvent() { }

        /// <summary>
        /// Initializes a new instance of the TextDocumentContentChangeEvent
        /// class.
        /// </summary>
        /// <param name="rangeLength">The length of the range that got
        /// replaced.</param>
        /// <param name="text">The new text of the document.</param>
        public TextDocumentContentChangeEvent(Range range = default(Range), double? rangeLength = default(double?), string text = default(string))
        {
            Range = range;
            RangeLength = rangeLength;
            Text = text;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "range")]
        public Range Range { get; set; }

        /// <summary>
        /// Gets or sets the length of the range that got replaced.
        /// </summary>
        [JsonProperty(PropertyName = "rangeLength")]
        public double? RangeLength { get; set; }

        /// <summary>
        /// Gets or sets the new text of the document.
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

    }
}

