// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An item to transfer a text document from the client to the server.
    /// </summary>
    public partial class TextDocumentItem
    {
        /// <summary>
        /// Initializes a new instance of the TextDocumentItem class.
        /// </summary>
        public TextDocumentItem() { }

        /// <summary>
        /// Initializes a new instance of the TextDocumentItem class.
        /// </summary>
        /// <param name="uri">The text document's URI.</param>
        /// <param name="languageId">The text document's language
        /// identifier.</param>
        /// <param name="version"> The version number of this document (it will
        /// strictly increase after each change, including undo/redo).</param>
        /// <param name="text">The content of the opened text document.</param>
        public TextDocumentItem(string uri = default(string), string languageId = default(string), double? version = default(double?), string text = default(string))
        {
            Uri = uri;
            LanguageId = languageId;
            Version = version;
            Text = text;
        }

        /// <summary>
        /// Gets or sets the text document's URI.
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

        /// <summary>
        /// Gets or sets the text document's language identifier.
        /// </summary>
        [JsonProperty(PropertyName = "languageId")]
        public string LanguageId { get; set; }

        /// <summary>
        /// Gets or sets  The version number of this document (it will strictly
        /// increase after each change, including undo/redo).
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public double? Version { get; set; }

        /// <summary>
        /// Gets or sets the content of the opened text document.
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

    }
}

