// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A parameter literal used in requests to pass a text document and a
    /// position inside that document.
    /// </summary>
    public partial class TextDocumentPositionParams
    {
        /// <summary>
        /// Initializes a new instance of the TextDocumentPositionParams class.
        /// </summary>
        public TextDocumentPositionParams() { }

        /// <summary>
        /// Initializes a new instance of the TextDocumentPositionParams class.
        /// </summary>
        public TextDocumentPositionParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier), Position position = default(Position))
        {
            TextDocument = textDocument;
            Position = position;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "position")]
        public Position Position { get; set; }

    }
}

