// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Capabilities specific to the textDocument/signatureHelp
    /// </summary>
    public partial class TextDocumentClientCapabilitiesSignatureHelp
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesSignatureHelp class.
        /// </summary>
        public TextDocumentClientCapabilitiesSignatureHelp() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesSignatureHelp class.
        /// </summary>
        /// <param name="dynamicRegistration">Whether signature help supports
        /// dynamic registration.</param>
        public TextDocumentClientCapabilitiesSignatureHelp(bool? dynamicRegistration = default(bool?))
        {
            DynamicRegistration = dynamicRegistration;
        }

        /// <summary>
        /// Gets or sets whether signature help supports dynamic registration.
        /// </summary>
        [JsonProperty(PropertyName = "dynamicRegistration")]
        public bool? DynamicRegistration { get; set; }

    }
}

