// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Text document specific client capabilities.
    /// </summary>
    public partial class TextDocumentClientCapabilities
    {
        /// <summary>
        /// Initializes a new instance of the TextDocumentClientCapabilities
        /// class.
        /// </summary>
        public TextDocumentClientCapabilities() { }

        /// <summary>
        /// Initializes a new instance of the TextDocumentClientCapabilities
        /// class.
        /// </summary>
        /// <param name="synchronization">syncronization specific
        /// capabilities</param>
        /// <param name="completion">Capabilities specific to the
        /// textDocument/completion</param>
        /// <param name="hover">Capabilities specific to the
        /// textDocument/hover</param>
        /// <param name="signatureHelp">Capabilities specific to the
        /// textDocument/signatureHelp</param>
        /// <param name="references">Capabilities specific to the
        /// textDocument/references</param>
        /// <param name="documentHighlight">Capabilities specific to the
        /// textDocument/references</param>
        /// <param name="documentSymbol">Capabilities specific to the
        /// textDocument/references</param>
        /// <param name="formatting">Capabilities specific to the
        /// textDocument/hover</param>
        /// <param name="rangeFormatting">Capabilities specific to the
        /// textDocument/hover</param>
        /// <param name="onTypeFormatting">Capabilities specific to the
        /// textDocument/hover</param>
        /// <param name="definition">Capabilities specific to the
        /// textDocument/hover</param>
        /// <param name="codeAction">Capabilities specific to the
        /// textDocument/hover</param>
        /// <param name="codeLens">Capabilities specific to the
        /// textDocument/hover</param>
        /// <param name="documentLink">Capabilities specific to the
        /// textDocument/hover</param>
        /// <param name="rename">Capabilities specific to the
        /// textDocument/hover</param>
        public TextDocumentClientCapabilities(TextDocumentClientCapabilitiesSynchronization synchronization = default(TextDocumentClientCapabilitiesSynchronization), TextDocumentClientCapabilitiesCompletion completion = default(TextDocumentClientCapabilitiesCompletion), TextDocumentClientCapabilitiesHover hover = default(TextDocumentClientCapabilitiesHover), TextDocumentClientCapabilitiesSignatureHelp signatureHelp = default(TextDocumentClientCapabilitiesSignatureHelp), TextDocumentClientCapabilitiesReferences references = default(TextDocumentClientCapabilitiesReferences), TextDocumentClientCapabilitiesDocumentHighlight documentHighlight = default(TextDocumentClientCapabilitiesDocumentHighlight), TextDocumentClientCapabilitiesDocumentSymbol documentSymbol = default(TextDocumentClientCapabilitiesDocumentSymbol), TextDocumentClientCapabilitiesFormatting formatting = default(TextDocumentClientCapabilitiesFormatting), TextDocumentClientCapabilitiesRangeFormatting rangeFormatting = default(TextDocumentClientCapabilitiesRangeFormatting), TextDocumentClientCapabilitiesOnTypeFormatting onTypeFormatting = default(TextDocumentClientCapabilitiesOnTypeFormatting), TextDocumentClientCapabilitiesDefinition definition = default(TextDocumentClientCapabilitiesDefinition), TextDocumentClientCapabilitiesCodeAction codeAction = default(TextDocumentClientCapabilitiesCodeAction), TextDocumentClientCapabilitiesCodeLens codeLens = default(TextDocumentClientCapabilitiesCodeLens), TextDocumentClientCapabilitiesDocumentLink documentLink = default(TextDocumentClientCapabilitiesDocumentLink), TextDocumentClientCapabilitiesRename rename = default(TextDocumentClientCapabilitiesRename))
        {
            Synchronization = synchronization;
            Completion = completion;
            Hover = hover;
            SignatureHelp = signatureHelp;
            References = references;
            DocumentHighlight = documentHighlight;
            DocumentSymbol = documentSymbol;
            Formatting = formatting;
            RangeFormatting = rangeFormatting;
            OnTypeFormatting = onTypeFormatting;
            Definition = definition;
            CodeAction = codeAction;
            CodeLens = codeLens;
            DocumentLink = documentLink;
            Rename = rename;
        }

        /// <summary>
        /// Gets or sets syncronization specific capabilities
        /// </summary>
        [JsonProperty(PropertyName = "synchronization")]
        public TextDocumentClientCapabilitiesSynchronization Synchronization { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/completion
        /// </summary>
        [JsonProperty(PropertyName = "completion")]
        public TextDocumentClientCapabilitiesCompletion Completion { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "hover")]
        public TextDocumentClientCapabilitiesHover Hover { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the
        /// textDocument/signatureHelp
        /// </summary>
        [JsonProperty(PropertyName = "signatureHelp")]
        public TextDocumentClientCapabilitiesSignatureHelp SignatureHelp { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/references
        /// </summary>
        [JsonProperty(PropertyName = "references")]
        public TextDocumentClientCapabilitiesReferences References { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/references
        /// </summary>
        [JsonProperty(PropertyName = "documentHighlight")]
        public TextDocumentClientCapabilitiesDocumentHighlight DocumentHighlight { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/references
        /// </summary>
        [JsonProperty(PropertyName = "documentSymbol")]
        public TextDocumentClientCapabilitiesDocumentSymbol DocumentSymbol { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "formatting")]
        public TextDocumentClientCapabilitiesFormatting Formatting { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "rangeFormatting")]
        public TextDocumentClientCapabilitiesRangeFormatting RangeFormatting { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "onTypeFormatting")]
        public TextDocumentClientCapabilitiesOnTypeFormatting OnTypeFormatting { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "definition")]
        public TextDocumentClientCapabilitiesDefinition Definition { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "codeAction")]
        public TextDocumentClientCapabilitiesCodeAction CodeAction { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "codeLens")]
        public TextDocumentClientCapabilitiesCodeLens CodeLens { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "documentLink")]
        public TextDocumentClientCapabilitiesDocumentLink DocumentLink { get; set; }

        /// <summary>
        /// Gets or sets capabilities specific to the textDocument/hover
        /// </summary>
        [JsonProperty(PropertyName = "rename")]
        public TextDocumentClientCapabilitiesRename Rename { get; set; }

    }
}

