// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// syncronization specific capabilities
    /// </summary>
    public partial class TextDocumentClientCapabilitiesSynchronization
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesSynchronization class.
        /// </summary>
        public TextDocumentClientCapabilitiesSynchronization() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesSynchronization class.
        /// </summary>
        /// <param name="dynamicRegistration">Whether text document
        /// synchronization supports dynamic registration.</param>
        /// <param name="willSave">The client supports sending will save
        /// notifications.</param>
        /// <param name="willSaveWaitUntil">The client supports sending a will
        /// save request and waits for a response providing text edits which
        /// will be applied to the document before it is saved.</param>
        /// <param name="didSave">The client supports did save
        /// notifications.</param>
        public TextDocumentClientCapabilitiesSynchronization(bool? dynamicRegistration = default(bool?), bool? willSave = default(bool?), bool? willSaveWaitUntil = default(bool?), bool? didSave = default(bool?))
        {
            DynamicRegistration = dynamicRegistration;
            WillSave = willSave;
            WillSaveWaitUntil = willSaveWaitUntil;
            DidSave = didSave;
        }

        /// <summary>
        /// Gets or sets whether text document synchronization supports dynamic
        /// registration.
        /// </summary>
        [JsonProperty(PropertyName = "dynamicRegistration")]
        public bool? DynamicRegistration { get; set; }

        /// <summary>
        /// Gets or sets the client supports sending will save notifications.
        /// </summary>
        [JsonProperty(PropertyName = "willSave")]
        public bool? WillSave { get; set; }

        /// <summary>
        /// Gets or sets the client supports sending a will save request and
        /// waits for a response providing text edits which will be applied to
        /// the document before it is saved.
        /// </summary>
        [JsonProperty(PropertyName = "willSaveWaitUntil")]
        public bool? WillSaveWaitUntil { get; set; }

        /// <summary>
        /// Gets or sets the client supports did save notifications.
        /// </summary>
        [JsonProperty(PropertyName = "didSave")]
        public bool? DidSave { get; set; }

    }
}

