// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Capabilities specific to the textDocument/references
    /// </summary>
    public partial class TextDocumentClientCapabilitiesReferences
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesReferences class.
        /// </summary>
        public TextDocumentClientCapabilitiesReferences() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesReferences class.
        /// </summary>
        /// <param name="dynamicRegistration">Whether references supports
        /// dynamic registration.</param>
        public TextDocumentClientCapabilitiesReferences(bool? dynamicRegistration = default(bool?))
        {
            DynamicRegistration = dynamicRegistration;
        }

        /// <summary>
        /// Gets or sets whether references supports dynamic registration.
        /// </summary>
        [JsonProperty(PropertyName = "dynamicRegistration")]
        public bool? DynamicRegistration { get; set; }

    }
}

