// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The document that will be saved.
    /// </summary>
    public partial class TextDocumentIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the TextDocumentIdentifier class.
        /// </summary>
        public TextDocumentIdentifier() { }

        /// <summary>
        /// Initializes a new instance of the TextDocumentIdentifier class.
        /// </summary>
        /// <param name="uri">The text document's URI.</param>
        public TextDocumentIdentifier(string uri = default(string))
        {
            Uri = uri;
        }

        /// <summary>
        /// Gets or sets the text document's URI.
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

    }
}

