// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Capabilities specific to the textDocument/completion
    /// </summary>
    public partial class TextDocumentClientCapabilitiesCompletion
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesCompletion class.
        /// </summary>
        public TextDocumentClientCapabilitiesCompletion() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TextDocumentClientCapabilitiesCompletion class.
        /// </summary>
        /// <param name="dynamicRegistration">hether completion supports
        /// dynamic registration.</param>
        /// <param name="completionItem">The client supports the following
        /// CompletionItem specific capabilities.</param>
        public TextDocumentClientCapabilitiesCompletion(bool? dynamicRegistration = default(bool?), TextDocumentClientCapabilitiesCompletionCompletionItem completionItem = default(TextDocumentClientCapabilitiesCompletionCompletionItem))
        {
            DynamicRegistration = dynamicRegistration;
            CompletionItem = completionItem;
        }

        /// <summary>
        /// Gets or sets hether completion supports dynamic registration.
        /// </summary>
        [JsonProperty(PropertyName = "dynamicRegistration")]
        public bool? DynamicRegistration { get; set; }

        /// <summary>
        /// Gets or sets the client supports the following CompletionItem
        /// specific capabilities.
        /// </summary>
        [JsonProperty(PropertyName = "completionItem")]
        public TextDocumentClientCapabilitiesCompletionCompletionItem CompletionItem { get; set; }

    }
}

