// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The document that did change. The version number points to the version
    /// after all provided content changes have been applied.
    /// </summary>
    public partial class VersionedTextDocumentIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the VersionedTextDocumentIdentifier
        /// class.
        /// </summary>
        public VersionedTextDocumentIdentifier() { }

        /// <summary>
        /// Initializes a new instance of the VersionedTextDocumentIdentifier
        /// class.
        /// </summary>
        /// <param name="version"> The version number of this document.</param>
        public VersionedTextDocumentIdentifier(double? version = default(double?))
        {
            Version = version;
        }

        /// <summary>
        /// Gets or sets  The version number of this document.
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public double? Version { get; set; }

    }
}

