// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The parameters send in a will save text document notification.
    /// </summary>
    public partial class WillSaveTextDocumentParams
    {
        /// <summary>
        /// Initializes a new instance of the WillSaveTextDocumentParams class.
        /// </summary>
        public WillSaveTextDocumentParams() { }

        /// <summary>
        /// Initializes a new instance of the WillSaveTextDocumentParams class.
        /// </summary>
        /// <param name="reason">The 'TextDocumentSaveReason'.</param>
        public WillSaveTextDocumentParams(TextDocumentIdentifier textDocument = default(TextDocumentIdentifier), int? reason = default(int?))
        {
            TextDocument = textDocument;
            Reason = reason;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; set; }

        /// <summary>
        /// Gets or sets the 'TextDocumentSaveReason'.
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public int? Reason { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Reason > 3)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Reason", 3);
            }
            if (Reason < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Reason", 1);
            }
        }
    }
}

