// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Workspace specific client capabilities.
    /// </summary>
    public partial class WorkspaceClientCapabilities
    {
        /// <summary>
        /// Initializes a new instance of the WorkspaceClientCapabilities
        /// class.
        /// </summary>
        public WorkspaceClientCapabilities() { }

        /// <summary>
        /// Initializes a new instance of the WorkspaceClientCapabilities
        /// class.
        /// </summary>
        /// <param name="applyEdit">The client supports applying batch edits to
        /// the workspace.</param>
        /// <param name="didChangeConfiguration">Did change configuration
        /// notification supports dynamic registration.</param>
        /// <param name="didChangeWatchedFiles">Did change watched files
        /// notification supports dynamic registration.</param>
        /// <param name="symbol">Symbol request supports dynamic
        /// registration.</param>
        /// <param name="executeCommand">Execute command supports dynamic
        /// registration.</param>
        public WorkspaceClientCapabilities(bool? applyEdit = default(bool?), WorkspaceCapabilitiesProps didChangeConfiguration = default(WorkspaceCapabilitiesProps), WorkspaceCapabilitiesProps didChangeWatchedFiles = default(WorkspaceCapabilitiesProps), WorkspaceCapabilitiesProps symbol = default(WorkspaceCapabilitiesProps), WorkspaceCapabilitiesProps executeCommand = default(WorkspaceCapabilitiesProps))
        {
            ApplyEdit = applyEdit;
            DidChangeConfiguration = didChangeConfiguration;
            DidChangeWatchedFiles = didChangeWatchedFiles;
            Symbol = symbol;
            ExecuteCommand = executeCommand;
        }

        /// <summary>
        /// Gets or sets the client supports applying batch edits to the
        /// workspace.
        /// </summary>
        [JsonProperty(PropertyName = "applyEdit")]
        public bool? ApplyEdit { get; set; }

        /// <summary>
        /// Gets or sets did change configuration notification supports dynamic
        /// registration.
        /// </summary>
        [JsonProperty(PropertyName = "didChangeConfiguration")]
        public WorkspaceCapabilitiesProps DidChangeConfiguration { get; set; }

        /// <summary>
        /// Gets or sets did change watched files notification supports dynamic
        /// registration.
        /// </summary>
        [JsonProperty(PropertyName = "didChangeWatchedFiles")]
        public WorkspaceCapabilitiesProps DidChangeWatchedFiles { get; set; }

        /// <summary>
        /// Gets or sets symbol request supports dynamic registration.
        /// </summary>
        [JsonProperty(PropertyName = "symbol")]
        public WorkspaceCapabilitiesProps Symbol { get; set; }

        /// <summary>
        /// Gets or sets execute command supports dynamic registration.
        /// </summary>
        [JsonProperty(PropertyName = "executeCommand")]
        public WorkspaceCapabilitiesProps ExecuteCommand { get; set; }

    }
}

