// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Capabilities specific to Workspace
    /// </summary>
    public partial class WorkspaceCapabilitiesProps
    {
        /// <summary>
        /// Initializes a new instance of the WorkspaceCapabilitiesProps class.
        /// </summary>
        public WorkspaceCapabilitiesProps() { }

        /// <summary>
        /// Initializes a new instance of the WorkspaceCapabilitiesProps class.
        /// </summary>
        public WorkspaceCapabilitiesProps(bool? dynamicRegistration = default(bool?))
        {
            DynamicRegistration = dynamicRegistration;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dynamicRegistration")]
        public bool? DynamicRegistration { get; set; }

    }
}

