// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientToServer.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A workspace edit represents changes to many resources managed in the
    /// workspace.
    /// </summary>
    public partial class WorkspaceEdit
    {
        /// <summary>
        /// Initializes a new instance of the WorkspaceEdit class.
        /// </summary>
        public WorkspaceEdit() { }

        /// <summary>
        /// Initializes a new instance of the WorkspaceEdit class.
        /// </summary>
        /// <param name="changes">Holds changes to existing resources.</param>
        public WorkspaceEdit(IList<TextEdit> changes = default(IList<TextEdit>))
        {
            Changes = changes;
        }

        /// <summary>
        /// Gets or sets holds changes to existing resources.
        /// </summary>
        [JsonProperty(PropertyName = "changes")]
        public IList<TextEdit> Changes { get; set; }

    }
}

